### ISSUE TITLE
Project Activity

### ISSUE THREAD

**Issue by mrianmerry** [bilskirnirr/pokemonta3#1]
Hey Blisk,

Ian here from the PTA 3 discord server - just wanted to drop by and ask if this is something you're still actively working on, or if you're happy for the project to be forked and development continued without your input.

The community has continued to use this as a base for a foundry system, but it appears that with v12 releasing some things no longer work.

I can get details on that if you'd prefer to handle maintenance and updates, but if we get no response in say, a week, then I'll make a fork.

---

Once you do return, if I've made a fork, I'll be happy to work on getting it merged back into this project so you can once more take control of your project.

**Comment by bilskirnirr** [comment]
Hello mrainmerry,

I have no concerns with someone taking over a fork and continuing development. I've had to table it project personally, so it would be great if someone could get it to take the steps for it to work for foundry v12.

thanks,
